blank_issues_enabled: false
contact_links:
  - name: Home Assistant Community Forum
    url: https://community.home-assistant.io
    about: For general Home Assistant questions, use the HA community forum.
  - name: HACS Documentation
    url: https://hacs.xyz
    about: For HACS-related issues, see the HACS documentation.
